# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "phom"
version = "0.1.0"
languages = ["C"]

[target.phom]
type = "executable"
sources = ["src/phom/*.c"]
compile-features = ["c_std_11"]
