name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Generate compile_commands.json
        run: |
          cmake -B build
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: "file"
          version: 17
          database: "build"
          tidy-review: true
          format-review: true
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
